name: build and deploy a static site
on:
  workflow_dispatch 
jobs:   
  job1: 
    permissions:
      contents: read
      pages: write
      id-token: write
    name: call the reusable workflow
    uses: deploy-static-websites/workflows/.github/workflows/build_deploy.yml@main
    with:
      build_source: '' # leave empty string '' if building from repo root
      build_destination: _site
      sparse_checkout: true # if true, action/checkout will checkout only build_source
      builder: jekyll
      deploy_to: gh-pages
      
