name: build and deploy a static site
on:
  workflow_dispatch 
env:
  build_source: '.'
jobs:   
  job1: 
    permissions:
      contents: read
      pages: write
      id-token: write
    name: call the reusable workflow
    uses: deploy-static-websites/workflows/.github/workflows/build_deploy.yml@main
    with:
      build_source: ${{env.build_source}}
      build_destination: _site
      sparse_checkout: ${{env.build_source}}
      builder: jekyll
      deploy_to: gh-pages
      
